version: 0.23
metadata:
  name: resource-choerodon
  namespace: c7n-system  # 指定命名空间安装choerodon
spec:
  persistence:
    storageClassName: nfs-provisioner
  resources:
    gitlab:
      domain: gitlab.c7n.yidaqiang.com
    minio:
      domain: minio.c7n.yidaqiang.com
    harbor:
      domain: harbor.c7n.yidaqiang.com
    chartmuseum:
      domain: chart.c7n.yidaqiang.com
    sonatype-nexus:
      domain: nexus.c7n.yidaqiang.com
    sonarqube:
      domain: sonarqube.c7n.yidaqiang.com
    choerodon-gateway:
      domain: api.c7n.yidaqiang.com
    choerodon-message:
      domain: notify.c7n.yidaqiang.com
    devops-service:
      domain: devops.c7n.yidaqiang.com
    choerodon-front:
      domain: app.c7n.yidaqiang.com
    choerodon-front-hzero:
      domain: hzero.c7n.yidaqiang.com
  helm:
    values:
      dir: manifests/values
