version: 0.22
metadata:
  name: resource-choerodon
  namespace: c7n-system  # 指定命名空间安装choerodon
spec:
  persistence:
    storageClassName: nfs-provisioner
  resources:
    mysql:
      external: false
    gitlab:
      domain: gitlab.dev.yidaqiang.com
      external: false
      #username: root     # gitlab 默认用户名为root，不能修改
      schema: http
    minio:
      domain: minio.dev.yidaqiang.com
      schema: http
    harbor:
      domain: harbor.dev.yidaqiang.com
      schema: https
      username: admin    # harbor 默认用户名为admin，不能修改
    chartmuseum:
      domain: chart.dev.yidaqiang.com
      schema: http
    hzero-gateway:
      domain: api.dev.yidaqiang.com
      schema: http
    hzero-message:
      domain: notify.dev.yidaqiang.com
      schema: ws
    devops-service:
      domain: devops.dev.yidaqiang.com
      schema: ws
    choerodon-front:
      domain: app.dev.yidaqiang.com
      schema: http
      username: admin   # 前端 默认用户名为admin，暂不能修改
      password: admin   # 前端 默认密码为admin，暂不能修改
    hzero-front:
      domain: hzero.dev.yidaqiang.com
      schema: http
  helm:
    values:
      dir: manifests/values