version: 0.21
metadata:
  name: resource-choerodon
  namespace: c7n-system  # 指定命名空间安装choerodon
spec:
  persistence:
    storageClassName: nfs-provisioner
  resources:
    mysql:
      external: false
    gitlab:
      domain: gitlab.test.yidaqiang.com
      external: false
      #username: root     # gitlab 默认用户名为root，不能修改
      schema: http
    minio:
      domain: minio.test.yidaqiang.com
      schema: http
    harbor:
      domain: harbor.test.yidaqiang.com
      schema: https
      username: admin    # harbor 默认用户名为admin，不能修改
    chartmuseum:
      domain: chart.test.yidaqiang.com
      schema: http
    api-gateway:
      domain: api.test.yidaqiang.com
      schema: http
    notify-service:
      domain: notify.test.yidaqiang.com
      schema: ws
    devops-service:
      domain: devops.test.yidaqiang.com
      schema: ws
    choerodon-front:
      domain: c7n.test.yidaqiang.com
      schema: http
      username: admin   # 前端 默认用户名为admin，暂不能修改
      password: admin   # 前端 默认密码为admin，暂不能修改
  helm:
    values:
      dir: manifests/values