version: 0.21
metadata:
  name: install-choerodon
  namespace: c7n-system  # 指定命名空间安装choerodon
spec:
  persistence:
    storageClassName: nfs-provisioner
  resources:
    mysql:
      external: false
    gitlab:
      domain: gitlab.example.choerodon.io
      external: false
      username: root     # gitlab 默认用户名为root，不能修改
      schema: http
    minio:
      domain: minio.example.choerodon.io
      schema: http
    harbor:
      domain: harbor.example.choerodon.io
      schema: https
      username: admin    # harbor 默认用户名为admin，不能修改
    chartmuseum:
      domain: chart.example.choerodon.io
      schema: http
    api-gateway:
      domain: api.example.choerodon.io
      schema: http
    notify-service:
      domain: notify.example.choerodon.io
      schema: ws
    devops-service:
      domain: devops.example.choerodon.io
      schema: ws
    choerodon-front:
      domain: c7n.example.choerodon.io
      schema: http
      username: admin   # 前端 默认用户名为admin，暂不能修改
      password: admin   # 前端 默认密码为admin，暂不能修改