apiVersion: v1
kind: Namespace
metadata:
  name: c7n-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: c7n-installer
  namespace: c7n-system

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: c7n-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: c7n-installer
  namespace: c7n-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-config
  namespace: c7n-system
data:
  install.yml: |-
    version: 0.11
    metadata:
      name: install-all
      namespace: c7n-system
    spec:
      persistence:
        storageClassName: nfs-provisioner
      resources:
        gitlab:
          domain: gitlab.example.com
          external: false
          username: root
          schema: http
        minio:
          domain: minio.example.com
          schema: http
        harbor:
          domain: harbor.example.com
          schema: https
        chartmuseum:
          domain: chart.example.com
          schema: http
        api-gateway:
          domain: api.example.com
          schema: http
        notify-service:
          domain: notify.example.com
          schema: ws
        choerodon-front:
          domain: front.example.com
          schema: http
        devops-service:
          domain: devops.example.com
          schema: ws
        choerodon-front:
          domain: c7n.example.com
          schema: http
        xwiki:
          domain: wiki.example.com

---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: resource-choerodon
  name: resource-choerodon
  namespace: c7n-system
spec:
  backoffLimit: 50
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: c7n-installer
      containers:
      - image: registry.cn-shanghai.aliyuncs.com/choerodon/c7n:0.1
        imagePullPolicy: Always
        name: resource-choerodon
        resources: {}
        volumeMounts:
        - name: config
          mountPath: /etc/c7n/
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: resource-config