env:
  open:
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ ( .GetResource "register-server").Url }}
    SPRING_CLOUD_CONFIG_URI: {{ (.GetResource "register-server").Schema }}://{{ (.GetResource "register-server").Host }}:{{ (.GetResource "register-server").Port }}
    SPRING_DATASOURCE_PASSWORD: {{ ( .GetInfra "base-service" ).GetPreValue "DATABASE_PASSWORD" }}
    SPRING_DATASOURCE_URL: {{ ( .GetInfra "base-service" ).GetPreValue "DATASOURCE_URL" }}
    SPRING_DATASOURCE_USERNAME: {{ ( .GetInfra "base-service" ).GetPreValue "DATABASE_USERNAME" }}
    SPRING_REDIS_DATABASE: 5
    SPRING_REDIS_HOST: {{ ( .GetResource "redis").Host }}
    SPRING_REDIS_PORT: {{ ( .GetResource "redis").Port }}
    SPRING_CACHE_MULTI_L1_ENABLED: true
    SPRING_CACHE_MULTI_L2_ENABLED: false
ingress:
  enabled: true
  host: {{ (.GetResource "api-gateway").Domain }}
preJob:
  timeout: 1800
service:
  enabled: true