preJob:
  timeout: 1800
  preInitDB:
    datasource:
      url: {{ .GetPreValue "DATASOURCE_URL" }}
      username: {{ .GetPreValue "DATABASE_USERNAME" }}
      password: {{ .GetPreValue "DATABASE_PASSWORD" }}
env:
  open:
    SPRING_CLOUD_CONFIG_URI: {{ (.GetResource "register-server").Schema }}://{{ (.GetResource "register-server").Host }}:{{ (.GetResource "register-server").Port }}
    SPRING_DATASOURCE_URL: {{ .GetPreValue "DATASOURCE_URL" }}
    SPRING_DATASOURCE_USERNAME: {{ .GetPreValue "DATABASE_USERNAME" }}
    SPRING_DATASOURCE_PASSWORD: {{ .GetPreValue "DATABASE_PASSWORD" }}
    SPRING_REDIS_HOST: {{ ( .GetResource "redis").Host }}
    SPRING_REDIS_PORT: {{ ( .GetResource "redis").Port }}
    SPRING_REDIS_DATABASE: 3
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ ( .GetResource "register-server").Url }}
    CHOERODON_GATEWAY_URL:  {{ .GetPreValue "API_GATEWAY_URL" }}