preJob:
  timeout: 1800
  preInitDB:
    datasource:
      url: {{ getDatabaseUrl "base_service" }}
      username: "choerodon"
      password: "password"
env:
  open:
    SPRING_CLOUD_CONFIG_URI: {{ (getResource "register-server").Schema }}://{{ (getResource "register-server").Host }}:{{ (getResource "register-server").Port }}
    SPRING_DATASOURCE_URL: {{ getDatabaseUrl "base_service" }}
    SPRING_DATASOURCE_USERNAME: "choerodon"
    SPRING_DATASOURCE_PASSWORD: "password"
    SPRING_REDIS_HOST: {{ ( getResource "redis").Host }}
    SPRING_REDIS_PORT: {{ ( getResource "redis").Port }}
    SPRING_REDIS_DATABASE: 3
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ ( getResource "register-server").Url }}
    CHOERODON_GATEWAY_URL:  '{{ ( getResource "api-gateway").Schema }}://{{ ( getResource "api-gateway").Domain }}'
