{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/redis
metrics:
  image: {{ .GetImageRepository }}/redis_exporter:latest
{{- end }}
persistence:
  enabled: true
  storageClass: {{ .GetStorageClass }}
service:
  enabled: true
