{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/chartmuseum
{{- end }}

env:
  open:
    AUTH_ANONYMOUS_GET: "true"
    STORAGE: local
    DISABLE_API: "false"
    DEPTH: 2
persistence:
  enabled: true
  storageClass: {{ .GetStorageClass }}
ingress:
  enabled: true
  hosts:
  - path: /
