{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/choerodon-gateway
{{- end }}

{{- if ne .GetImageRepository "" }}
## 插件相关配置
plugins:
  # skywalking agent 镜像地址
  skywalkingAgentImage: {{ .GetImageRepository }}/skywalking-agent:6.6.0
{{- end }}

env:
  open:
    SPRING_REDIS_HOST: {{ ( .GetResource "c7n-redis").Host }}
    SPRING_REDIS_PORT: {{ ( .GetResource "c7n-redis").Port }}
    # 此db不可更改
    SPRING_REDIS_DATABASE: 4
    SPRING_DATASOURCE_URL: {{ .GetDatabaseUrl "hzero_platform" }}
    SPRING_DATASOURCE_USERNAME: choerodon
    SPRING_DATASOURCE_PASSWORD: password
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .GetEurekaUrl }}
ingress:
  enabled: true
{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi
{{- end }}