ingress:
  enabled: true
env:
  open:
    BUILD_CLIENT_ID: hzero
    BUILD_API_HOST: {{ .GetResourceDomainUrl "choerodon-gateway" }}
    BUILD_WEBSOCKET_HOST: {{ .GetResourceDomainUrl "choerodon-gateway" }}/hpfm/sock-js
{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi
{{- end }}