{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/code-repo-service
{{- end }}

{{- if ne .GetImageRepository "" }}
## 插件相关配置
plugins:
  # skywalking agent 镜像地址
  skywalkingAgentImage: {{ .GetImageRepository }}/skywalking-agent:6.6.0
{{- end }}

initDatabases:
  datasource:
    url: {{ .GetDatabaseUrl "" }}
    username: choerodon
    password: password
  datasources:
    # 多数据源初始化 初始化菜单数据
    # 支持框架数据和agile进行分库 指定菜单初始化地址
    platform:
      url: {{ .GetDatabaseUrl "" }}
      username: choerodon
      password: password
extraEnv:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .GetEurekaUrl }}
  GITLAB_PRIVATETOKEN: {{ .GetReleaseValue "gitlab-service" "extraEnv.GITLAB_PRIVATETOKEN" }}
  GITLAB_URL: {{ .GetResourceDomainUrl "gitlab" }}
  SPRING_DATASOURCE_URL: {{ .GetDatabaseUrl "hrds_code_repo" }}
  SPRING_DATASOURCE_USERNAME: choerodon
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_REDIS_DATABASE: 0
  SPRING_REDIS_HOST: {{ ( .GetResource "c7n-redis").Host }}
  SPRING_REDIS_PORT: {{ ( .GetResource "c7n-redis").Port }}
{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi
{{- end }}