env:
  open:
    AGENT_CERTMANAGERURL: https://openchart.choerodon.com.cn/choerodon/c7n/
    AGENT_REPOURL: https://openchart.choerodon.com.cn/choerodon/c7n/
    AGENT_SERVICEURL: ws://{{ ( getResource "devops-service").Domain }}/agent/
    AGENT_VERSION: 0.21.0
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ ( getResource "register-server").Url }}
    SERVICES_GATEWAY_URL: {{ ( getResource "api-gateway").Schema }}://{{ (getResource "api-gateway").Domain }}
    # TODO add get values method
    SERVICES_GITLAB_PASSWORD: "password"
    SERVICES_GITLAB_SSHURL: {{ ( getResource "gitlab-ha").Domain }}:32222
    SERVICES_GITLAB_URL: {{ ( getResource "gitlab-ha").Schema }}://{{ ( getResource "gitlab-ha").Domain }}
    SERVICES_HARBOR_BASEURL: {{ ( getResource "harbor").Schema }}://{{ ( getResource "harbor").Domain }}
    SERVICES_HARBOR_PASSWORD: {{ ( getResource "harbor" ).Password }}
    SERVICES_HELM_URL: {{ ( getResource "gitlab-ha").Schema }}://{{ ( getResource "gitlab-ha").Domain }}
    SPRING_CLOUD_CONFIG_URI: {{ ( getResource "register-server").Schema }}://{{ ( getResource "register-server").Host }}:{{ ( getResource "register-server").Port }}
    SPRING_DATASOURCE_PASSWORD: "password"
    SPRING_DATASOURCE_URL: {{ getDatabaseUrl "devops_service" }}
    SPRING_DATASOURCE_USERNAME: "choerodon"
    SPRING_REDIS_DATABASE: 7
    SPRING_REDIS_HOST: {{ ( getResource "redis").Host }}
    SPRING_REDIS_PORT: {{ ( getResource "redis").Port }}
ingress:
  enabled: true
  host: {{ ( getResource "devops-service").Domain }}
preJob:
  timeout: 1800
  preInitDB:
    datasource:
      url: {{ getDatabaseUrl "devops_service" }}
      username: "choerodon"
      password: "password"
service:
  enabled: true
