env:
  open:
    AGENT_CERTMANAGERURL: https://openchart.choerodon.com.cn/choerodon/c7n/
    AGENT_REPOURL: https://openchart.choerodon.com.cn/choerodon/c7n/
    AGENT_SERVICEURL: ws://{{ (.GetResource "devops-service").Domain }}/agent/
    AGENT_VERSION: 0.21.0
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ ( .GetResource "register-server").Url }}
    SERVICES_GATEWAY_URL: {{ ( .GetResource "api-gateway").Schema }}://{{ (.GetResource "api-gateway").Domain }}
    SERVICES_GITLAB_PASSWORD: {{ .GetPreValue "DEFAULT_GIT_PASSWORD" }}
    SERVICES_GITLAB_SSHURL: {{ ( .GetInfra "gitlab" ).GetPreValue "GITLAB_BASE_DOMAIN" }}:32222
    SERVICES_GITLAB_URL: {{ ( .GetInfra "gitlab" ).GetPreValue "GITLAB_BASE_SCHEMA" }}://{{ ( .GetInfra "gitlab" ).GetPreValue "GITLAB_BASE_DOMAIN" }}
    SERVICES_HARBOR_BASEURL: {{ ( .GetInfra "harbor" ).GetValue "externalURL" }}
    SERVICES_HARBOR_PASSWORD: {{ ( .GetInfra "harbor" ).GetValue "harborAdminPassword" }}
    SERVICES_HELM_URL: {{ ( .GetInfra "chartmuseum" ).GetPreValue "CHART_BASE_SCHEMA" }}://{{ ( .GetInfra "chartmuseum" ).GetPreValue "CHART_BASE_DOMAIN" }}
    SPRING_CLOUD_CONFIG_URI: {{ (.GetResource "register-server").Schema }}://{{ (.GetResource "register-server").Host }}:{{ (.GetResource "register-server").Port }}
    SPRING_DATASOURCE_PASSWORD: {{ .GetPreValue "DATABASE_PASSWORD" }}
    SPRING_DATASOURCE_URL: {{ .GetPreValue "DATASOURCE_URL" }}
    SPRING_DATASOURCE_USERNAME: {{ .GetPreValue "DATABASE_USERNAME" }}
    SPRING_REDIS_DATABASE: 7
    SPRING_REDIS_HOST: {{ ( .GetResource "redis").Host }}
    SPRING_REDIS_PORT: {{ ( .GetResource "redis").Port }}
ingress:
  enabled: true
  host: {{ (.GetResource "devops-service").Domain }}
preJob:
  timeout: 1800
  preInitDB:
    datasource:
      url: {{ .GetPreValue "DATASOURCE_URL" }}
      username: {{ .GetPreValue "DATABASE_USERNAME" }}
      password: {{ .GetPreValue "DATABASE_PASSWORD" }}
service:
  enabled: true