{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/devops-service
{{- end }}

{{- if ne .GetImageRepository "" }}
## 插件相关配置
plugins:
  # skywalking agent 镜像地址
  skywalkingAgentImage: {{ .GetImageRepository }}/skywalking-agent:6.6.0
{{- end }}

preJob:
{{- if ne .GetImageRepository "" }}
  image: {{ .GetImageRepository }}/dbtool:0.7.1
{{- end }}
  preInitDB:
    datasource:
      url: {{ .GetDatabaseUrl "" }}
      username: choerodon
      password: password
    datasources:
      # 多数据源初始化 初始化菜单数据
      platform:
        url: {{ .GetDatabaseUrl "" }}
        username: choerodon
        password: password
        driver: com.mysql.jdbc.Driver
env:
  open:
    SPRING_REDIS_HOST: {{ ( .GetResource "redis").Host }}
    SPRING_REDIS_PORT: {{ ( .GetResource "redis").Port }}
    SPRING_REDIS_DATABASE: 9
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .GetEurekaUrl }}
    SPRING_DATASOURCE_URL: {{ .GetDatabaseUrl "devops_service" }}
    SPRING_DATASOURCE_USERNAME: "choerodon"
    SPRING_DATASOURCE_PASSWORD: "password"
    SERVICES_GITLAB_URL: {{ .GetResourceDomainUrl "gitlab" }}
    SERVICES_GITLAB_SSHURL: {{ ( .GetResource "gitlab").Domain }}:30022
    SERVICES_GITLAB_PROJECTLIMIT: 100
    SERVICES_HELM_URL: {{ .GetResourceDomainUrl "chartmuseum" }}
    SERVICES_HARBOR_BASEURL: {{ .GetResourceDomainUrl "harbor" }}
    SERVICES_HARBOR_USERNAME: admin
    SERVICES_HARBOR_PASSWORD: {{ .GetReleaseValue "harbor" "harborAdminPassword" }}
    SERVICES_HARBOR_INSECURESKIPTLSVERIFY: true
    SERVICES_GATEWAY_URL: {{ .GetResourceDomainUrl "hzero-gateway" }}
    AGENT_VERSION: 0.22.3
    AGENT_SERVICEURL: {{ .GetResourceDomainUrl "devops-service" }}/websocket
    AGENT_REPOURL: http://openchart.choerodon.com.cn/choerodon/c7n/
    AGENT_CERTMANAGERURL: http://openchart.choerodon.com.cn/choerodon/c7n/
    #SERVICES_SONARQUBE_URL: http://sonarqube.example.choerodon.io
    #SERVICES_SONARQUBE_USERNAME: admin
    #SERVICES_SONARQUBE_PASSWORD: admin
    # 以下是开发日志配置， 不要用于生产环境
    #LOGGING_LEVEL_COM_NETFLIX: warn
    #OGGING_LEVEL_IO_CHOERODON_DEVOPS_INFRA_HANDLER: debug
ingress:
  enabled: true

{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi
{{- end }}
