{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/workflow_service
{{- end }}

{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi
{{- end }}