{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/elasticsearch-kb
{{- end }}

{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 2Gi
  requests:
    # cpu: 100m
    memory: 2Gi
{{- end }}