env:
  open:
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ ( .GetResource "register-server").Url }}
    GITLAB_PRIVATETOKEN: {{ .GetPreValue "GITLAB_OAUTH_TOKEN" }}
    GITLAB_URL: {{ ( .GetInfra "gitlab" ).GetPreValue "GITLAB_BASE_SCHEMA" }}://{{ ( .GetInfra "gitlab" ).GetPreValue "GITLAB_BASE_DOMAIN" }}
    SPRING_CLOUD_CONFIG_URI: {{ (.GetResource "register-server").Schema }}://{{ (.GetResource "register-server").Host }}:{{ (.GetResource "register-server").Port }}
    SPRING_DATASOURCE_PASSWORD: {{ .GetPreValue "DATABASE_PASSWORD" }}
    SPRING_DATASOURCE_URL: {{ .GetPreValue "DATASOURCE_URL" }}
    SPRING_DATASOURCE_USERNAME: {{ .GetPreValue "DATABASE_USERNAME" }}
preJob:
  timeout: 1800
  preInitDB:
    datasource:
      url: {{ .GetPreValue "DATASOURCE_URL" }}
      username: {{ .GetPreValue "DATABASE_USERNAME" }}
      password: {{ .GetPreValue "DATABASE_PASSWORD" }}