{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/gitlab-service
{{- end }}

{{- if ne .GetImageRepository "" }}
## 插件相关配置
plugins:
  # skywalking agent 镜像地址
  skywalkingAgentImage: {{ .GetImageRepository }}/skywalking-agent:6.6.0
{{- end }}

extraEnv:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .GetEurekaUrl }}
  GITLAB_URL: {{ .GetResourceDomainUrl "gitlab" }}
  SPRING_REDIS_HOST: {{ ( .GetResource "c7n-redis").Host }}
  SPRING_REDIS_PORT: {{ ( .GetResource "c7n-redis").Port }}
  SPRING_REDIS_DATABASE: 14
{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi
{{- end }}
