externalURL: {{ .GetResourceDomainUrl "harbor" }}

persistence:
  persistentVolumeClaim:
    database:
      storageClass: {{ .GetStorageClass }}
    registry:
      storageClass: {{ .GetStorageClass }}
    jobservice:
      storageClass: {{ .GetStorageClass }}
    redis:
      storageClass: {{ .GetStorageClass }}

chartmuseum:
  enabled: false
notary:
  enabled: false
clair:
  enabled: false