ingress:
  enabled: true
env:
  open:
    BUILD_CLIENT_ID: hzero
    BUILD_API_HOST: {{ .GetResourceDomainUrl "hzero-front" }}
{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi
{{- end }}