env:
  open:
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .GetEurekaUrl }}
    HZERO_OAUTH_URL: {{ .GetResourceDomainUrl "hzero-gateway" }}/oauth/oauth/authorize
    SPRING_REDIS_HOST: {{ ( .GetResource "redis").Host }}
    SPRING_REDIS_PORT: {{ ( .GetResource "redis").Port }}
    # 此db不可更改
    SPRING_REDIS_DATABASE: 1
    SPRING_DATASOURCE_URL: {{ .GetDatabaseUrl "hzero_admin" }}
    SPRING_DATASOURCE_USERNAME: choerodon
    SPRING_DATASOURCE_PASSWORD: password