{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/hzero-file
{{- end }}

{{- if ne .GetImageRepository "" }}
## 插件相关配置
plugins:
  # skywalking agent 镜像地址
  skywalkingAgentImage: {{ .GetImageRepository }}/skywalking-agent:6.6.0
{{- end }}

preJob:
{{- if ne .GetImageRepository "" }}
  image: {{ .GetImageRepository }}/dbtool:0.7.1
{{- end }}
  preInitDB:
    datasource:
      url: {{ .GetDatabaseUrl "" }}
      username: choerodon
      password: password
      driver: com.mysql.jdbc.Driver
env:
  open:
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .GetEurekaUrl }}
    SPRING_REDIS_HOST: {{ ( .GetResource "redis").Host }}
    SPRING_REDIS_PORT: {{ ( .GetResource "redis").Port }}
    # 此db不可更改
    SPRING_REDIS_DATABASE: 1
    SPRING_DATASOURCE_URL: {{ .GetDatabaseUrl "hzero_file" }}
    SPRING_DATASOURCE_USERNAME: choerodon
    SPRING_DATASOURCE_PASSWORD: password
    SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 200MB
    SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 200MB
    FILE_GATEWAY_URL: {{ .GetResourceDomainUrl "hzero-gateway" }}/hfle
    MINIO_ACCESSKEY: {{ .GetReleaseValue "minio" "accessKey" }}
    MINIO_ENDPOINT: {{ .GetResourceDomainUrl "minio" }}
    MINIO_SECRETKEY: {{ .GetReleaseValue "minio" "secretKey" }}
{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi
{{- end }}