{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/hzero_oauth
{{- end }}

{{- if ne .GetImageRepository "" }}
## 插件相关配置
plugins:
  # skywalking agent 镜像地址
  skywalkingAgentImage: {{ .GetImageRepository }}/skywalking-agent:6.6.0
{{- end }}

env:
  open:
    # 如果使用https 该参数设置为true
    HZERO_OAUTH_LOGIN_ENABLE_HTTPS: false
    HZERO_OAUTH_LOGIN_SUCCESS_URL: {{ .GetResourceDomainUrl "choerodon-front" }}
    HZERO_OAUTH_LOGIN_DEFAULT_CLIENT_ID: choerodon
    HZERO_GATEWAY_URL: {{ .GetResourceDomainUrl "hzero-gateway" }}
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .GetEurekaUrl }}
    SPRING_DATASOURCE_URL: {{ .GetDatabaseUrl "hzero_platform" }}
    SPRING_DATASOURCE_USERNAME: choerodon
    SPRING_DATASOURCE_PASSWORD: password
    SPRING_REDIS_HOST: {{ ( .GetResource "redis").Host }}
    SPRING_REDIS_PORT: {{ ( .GetResource "redis").Port }}
    # 此db不可更改
    SPRING_REDIS_DATABASE: 3
{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi
{{- end }}