env:
  open:
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ ( getResource "register-server").Url }}
    SERVICES_ATTACHMENT_URL: {{ ( getResource "minio").Schema }}://{{ ( getResource "minio").Domain }}
    SPRING_CLOUD_CONFIG_URI: {{ ( getResource "register-server").Schema }}://{{ ( getResource "register-server").Host }}:{{ ( getResource "register-server").Port }}
    SPRING_DATASOURCE_PASSWORD: "password"
    SPRING_DATASOURCE_URL: {{ getDatabaseUrl "knowledgebase_service" }}
    SPRING_DATASOURCE_USERNAME: "choerodon"
    ELASTICSEARCH_IP: {{ ( getResource "elasticsearch-kb").Host }}:{{ ( getResource "elasticsearch-kb").Port }}
preJob:
  timeout: 1800
  preInitDB:
    datasource:
      url: {{ getDatabaseUrl "knowledgebase_service" }}
      username: "choerodon"
      password: "password"
  preConfig:
    updatePolicy: override  