env:
  open:
    CHOERODON_GATEWAY_DOMAIN: {{ ( .getResource "api-gateway").Domain }}
    CHOERODON_SWAGGER_OAUTH_URL: {{ ( .getResource "api-gateway").Schema }}://{{ ( .getResource "api-gateway").Domain }}/oauth/oauth/authorize
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ ( .getResource "register-server").Url }}
    SPRING_CLOUD_CONFIG_URI: {{ ( .getResource "register-server").Schema }}://{{ ( .getResource "register-server").Host }}:{{ (.getResource "register-server").Port }}
    SPRING_DATASOURCE_PASSWORD: "password"
    SPRING_DATASOURCE_URL: {{ .getDatabaseUrl "manager_service" }}
    SPRING_DATASOURCE_USERNAME: "choerodon"
    SPRING_REDIS_DATABASE: 1
    SPRING_REDIS_HOST: {{ ( .getResource "redis").Host }}
    SPRING_REDIS_PORT: {{ ( .getResource "redis").Port }}
preJob:
  timeout: 1800
  preInitDB:
    datasource:
      # TODO get manager method
      password: "password"
      url: {{ .getDatabaseUrl "manager_service" }}
      username: "choerodon"