env:
  open:
    CHOERODON_GATEWAY_DOMAIN: {{ ( .GetResource "api-gateway").Domain }}
    CHOERODON_SWAGGER_OAUTH_URL: {{ .GetPreValue "API_GATEWAY_URL" }}/oauth/oauth/authorize
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ ( .GetResource "register-server").Url }}
    SPRING_CLOUD_CONFIG_URI: {{ (.GetResource "register-server").Schema }}://{{ (.GetResource "register-server").Host }}:{{ (.GetResource "register-server").Port }}
    SPRING_DATASOURCE_PASSWORD: {{ .GetPreValue "DATABASE_PASSWORD" }}
    SPRING_DATASOURCE_URL: {{ .Call "GetManagerDatasource" }}
    SPRING_DATASOURCE_USERNAME: {{ .GetPreValue "DATABASE_USERNAME" }}
    SPRING_REDIS_DATABASE: 1
    SPRING_REDIS_HOST: {{ ( .GetResource "redis").Host }}
    SPRING_REDIS_PORT: {{ ( .GetResource "redis").Port }}
preJob:
  timeout: 1800
  preInitDB:
    datasource:
      password: {{ .Call "GetManagerDatabasePassword" }}
      url: {{ .Call "GetManagerDatasource" }}
      username: {{ .Call "GetManagerDatabaseUsername" }}