env:
  open:
    CHOERODON_DEFAULT_REDIRECT_URL: {{ ( getResource "choerodon-front").Schema }}://{{ ( getResource "choerodon-front").Domain }}
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ ( getResource "register-server").Url }}
    SPRING_CLOUD_CONFIG_URI: {{ (getResource "register-server").Schema }}://{{ (getResource "register-server").Host }}:{{ (getResource "register-server").Port }}
    SPRING_DATASOURCE_PASSWORD: "password"
    SPRING_DATASOURCE_URL: {{ getDatabaseUrl "base_service" }}
    SPRING_DATASOURCE_USERNAME: "choerodon"
    SPRING_REDIS_DATABASE: 6
    SPRING_REDIS_HOST: {{ ( getResource "redis").Host }}
preJob:
  timeout: 1800