{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/prod-repo-service
{{- end }}

{{- if ne .GetImageRepository "" }}
## 插件相关配置
plugins:
  # skywalking agent 镜像地址
  skywalkingAgentImage: {{ .GetImageRepository }}/skywalking-agent:6.6.0
{{- end }}

preJob:
{{- if ne .GetImageRepository "" }}
  image: {{ .GetImageRepository }}/dbtool:0.7.1
{{- end }}
  preInitDB:
    datasource:
      url: {{ .GetDatabaseUrl "" }}
      username: choerodon
      password: password
    datasources:
      # 多数据源初始化 初始化菜单数据
      # 支持框架数据和agile进行分库 指定菜单初始化地址
      platform:
        url: {{ .GetDatabaseUrl "" }}
        username: choerodon
        password: password
        driver: com.mysql.jdbc.Driver
extraEnv:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .GetEurekaUrl }}
  HARBOR_BASE_URL: {{ .GetResourceDomainUrl "harbor" }}
  HARBOR_PASSWORD: {{ .GetReleaseValue "harbor" "harborAdminPassword" }}
  HARBOR_USER_NAME: admin
  HARBOR_API_VERSION: v2
  SPRING_DATASOURCE_URL: {{ .GetDatabaseUrl "hrds_prod_repo" }}
  SPRING_DATASOURCE_USERNAME: choerodon
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_REDIS_DATABASE: 0
  SPRING_REDIS_HOST: {{ ( .GetResource "c7n-redis").Host }}
  SPRING_REDIS_PORT: {{ ( .GetResource "c7n-redis").Port }}
  NEXUS_DEFAULT_BASE_URL: {{ .GetResourceDomainUrl "sonatype-nexus" }}
  NEXUS_DEFAULT_ENABLE_ANONYMOUS_FLAG: 0
  NEXUS_DEFAULT_PASSWORD: {{ .GetReleaseValue "sonatype-nexus" "initAdminPassword.password" }}
  NEXUS_PROXY_URIPREFIX: /v1/nexus/proxy
  NEXUS_PROXY_SERVLETURI: /v1/nexus/proxy/*
  SERVICES_GATEWAY_URL: {{ .GetResourceDomainUrl "choerodon-gateway" }}
  SERVICE_ROUTE: /rdupm
{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi
{{- end }}