persistence:
  enabled: true
  storageClass: {{ .GetStorageClass }}
postgresql:
  persistence:
    storageClass: {{ .GetStorageClass }}
ingress:
  enabled: true
plugins:
  install:
    - 'https://file.choerodon.com.cn/choerodon-install/sonarqube/sonar-auth-choerodonoauth-plugin-1.5.4.RELEASE.jar'