persistence:
  enabled: true
  storageClass: {{ .GetStorageClass }}
postgresql:
  enabled: true
  primary:
    persistence:
      storageClass: {{ .GetStorageClass }}
      size: 50Gi
ingress:
  enabled: true
sonarqubePassword: "password"
sonarqubeUsername: admin
