preJob:
  preInitDB:
    datasource:
      url: {{ .GetDatabaseUrl "" }}
      username: choerodon
      password: password
    datasources:
      # 多数据源初始化
      # 支持框架数据和agile进行分库 指定菜单初始化地址
      platform:
        url: {{ .GetDatabaseUrl "" }}
        username: choerodon
        password: password
        driver: com.mysql.jdbc.Driver
env:
  open:
    SPRING_REDIS_HOST: {{ ( .GetResource "redis").Host }}
    SPRING_REDIS_PORT: {{ ( .GetResource "redis").Port }}
    SPRING_REDIS_DATABASE: 13
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .GetEurekaUrl }}
    SPRING_DATASOURCE_URL: {{ .GetDatabaseUrl "test_manager_service" }}
    SPRING_DATASOURCE_USERNAME: choerodon
    SPRING_DATASOURCE_PASSWORD: password
    CHOERODON_CLEANPERMISSION: false
    SERVICES_ATTACHMENT_URL: {{ .GetResourceDomainUrl "minio" }}