{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/test-manager-service
{{- end }}

{{- if ne .GetImageRepository "" }}
## 插件相关配置
plugins:
  # skywalking agent 镜像地址
  skywalkingAgentImage: {{ .GetImageRepository }}/skywalking-agent:6.6.0
{{- end }}

preJob:
{{- if ne .GetImageRepository "" }}
  image: {{ .GetImageRepository }}/dbtool:0.7.1
{{- end }}
  preInitDB:
    datasource:
      url: {{ .GetDatabaseUrl "" }}
      username: choerodon
      password: password
    datasources:
      # 多数据源初始化
      # 支持框架数据和agile进行分库 指定菜单初始化地址
      platform:
        url: {{ .GetDatabaseUrl "" }}
        username: choerodon
        password: password
        driver: com.mysql.jdbc.Driver
env:
  open:
    SPRING_REDIS_HOST: {{ ( .GetResource "c7n-redis").Host }}
    SPRING_REDIS_PORT: {{ ( .GetResource "c7n-redis").Port }}
    SPRING_REDIS_DATABASE: 13
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .GetEurekaUrl }}
    SPRING_DATASOURCE_URL: {{ .GetDatabaseUrl "test_manager_service" }}
    SPRING_DATASOURCE_USERNAME: choerodon
    SPRING_DATASOURCE_PASSWORD: password
    CHOERODON_CLEANPERMISSION: false
    SERVICES_ATTACHMENT_URL: {{ .GetResourceDomainUrl "minio" }}
{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi
{{- end }}

