{{- if ne .GetImageRepository "" }}
image:
  repository: {{ .GetImageRepository }}/workflow-service
{{- end }}

{{- if ne .GetImageRepository "" }}
## 插件相关配置
plugins:
  # skywalking agent 镜像地址
  skywalkingAgentImage: {{ .GetImageRepository }}/skywalking-agent:6.6.0
{{- end }}

env:
  open:
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .GetEurekaUrl }}
    SPRING_DATASOURCE_URL: {{ .GetDatabaseUrl "workflow_service" }}
    SPRING_DATASOURCE_USERNAME: choerodon
    SPRING_DATASOURCE_PASSWORD: password
{{- if .IsThinMode }}
resources:
  limits:
    # cpu: 100m
    memory: 1Gi
  requests:
    # cpu: 100m
    memory: 1Gi
{{- end }}